### ISSUE TITLE
Issue with circuit

### ISSUE THREAD

**Issue by mzeeqazi** [eddieoz/haal#2]
Am trying to develop something similar. But I didn't get how you get circuits. I tried to develop election for only one post ( the president), but am stuck at these circuits. Do you use some script or so?

**Comment by eddieoz** [comment]
For that you need 2 things:
- Package Circom: `npm install -g circom`
- Clone the circomlib repository in some place: https://github.com/iden3/circomlib

Point the first line (`include "../../../../circomlib/circuits/comparators.circom"`) of `zksnarks/circuits/vote-proof1.circom` to your circomlib repository

Then, run `# circom vote-proof1.circom -o vote-proof1.json` to compile the circuit

You will use the json file as running circuit to your zksnarks

**Comment by mzeeqazi** [comment]
Thanks @eddieoz
 ps: do you have plans to upgrade contracts for solc 0.5 or above. If yes, I can contribute to it
