### ISSUE TITLE
Contato

### ISSUE THREAD

**Issue by MIQUEIASGAMA** [eddieoz/haal#7]
Boa tarde Mestre, tudo bem?

Me interessei muito pelas funções da plataforma originalmy, interessante, vou deixar meu e-mail 
gostaria de tirar umas duvidas acredito que você tem um conhecimento mega amplo em blockchain, me chamo Miqueias sou CEO e desenvolvedor do token Fitcash FTH

www.fitcash.co
miqueiasgamaferreira@gmail.com
(11)96591-1295

**Comment by eddieoz** [comment]
Miqueias, sobre as funcionalidades da OriginalMy, eu te peço a gentileza de entrar em contato conosco através do email contato at originalmy.com

Att,
